###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

_site_url: _site_url
_log_level: debug
_display_debug_panel: true
